### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by flimo44** [jystervinou/freebox-caller-id#1]
pi@Pi2:~/freebox-caller-id $ sudo node caller_id.js init
/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:50
class Freebox extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/freebox-caller-id/caller_id.js:1:77)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by jystervinou** [comment]
Hello,

Quelle version de Node ? le module node-freeboxos nécessite une version 6 minimum je crois.

**Comment by flimo44** [comment]
Bonjour

Node est en version 5.
Je vais voir pour passer en 6.

Cdlt
Philippe

**Comment by jystervinou** [comment]
Visiblement, quelqu'un d'autre me signale que ce n'est pas simple voir pas possible d'upgrader node sur les raspberry avec un armv6...

**Comment by flimo44** [comment]
Bonjour ,
Update effectué en version 6 . Le problème semble resolu.

Pour faire l'update en node 6  sur RP2 et RPI3 ( RPI1 je n'ai pas testé )

Ajouter le repository nodesource :
sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
Cette commande va aussi  mettre à jour le catalogue.
 
NB. Adafuit mets aussi node à disposition sur un repository similaire. Avec nodesource, on a une version plus à jour. 
NB. Quand la version 8 de NodeJS sera disponible, l'url ci-dessus devra être adaptée. Voir https://github.com/nodejs/LTS/.
 
Installer nodejs :
sudo apt-get install nodejs
NB. npm (le gestionnaire de package de node) est installé automatiquement avec nodejs.
 
Vérification :
pi@raspberrypi:~ $ nodejs -v
v6.2.1
pi@raspberrypi:~ $ npm -v
3.9.3

**Comment by flimo44** [comment]
Bonjour ,
Voici l'erreur que j'ai au lancement du script principale : 


pi@Pi2:~/freebox-caller-id $ sudo node caller_id.js
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/callerid/freebox.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at new Freebox (/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:65:22)
    at getCalls (/home/pi/freebox-caller-id/caller_id.js:96:17)
    at run (/home/pi/freebox-caller-id/caller_id.js:57:3)
    at Object.<anonymous> (/home/pi/freebox-caller-id/caller_id.js:54:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

Ps :  J'avais pas vu l'erreur avant lors de l'init d'ou l'erreur ci-dessus.
J'ai pourtant bien validé sur l'écran de la freebox  "Oui"  :( 

pi@Pi2:~/freebox-caller-id $ sudo node caller_id.js init
error= null app= { app_id: 'callerid',
  app_name: 'Caller ID',
  app_version: '0.0.1',
  device_name: 'Server',
  app_token: 'xxxxxxxxxxxxxxxxxxxxxxxxfCgR1QRd5rzIoXIf8POngnpSY49ij/YPYY8t/dE',
  track_id: 3,
  logged_in: false,
  challenge: 'YeJCnECFUU7hqLOCIhtyj/Wr4EhbmUxX',
  password: null,
  status: 'granted' }
fs.js:81
  throw new TypeError('Expected options to be either an object or a string, ' +
  ^

TypeError: Expected options to be either an object or a string, but got function instead
    at throwOptionsError (fs.js:81:9)
    at Object.fs.writeFileSync (fs.js:1341:5)
    at Freebox._saveJSON (/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:132:6)
    at P (/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:121:31)
    at P (/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:1569:3)
    at Freebox.saveJSON (/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:121:10)
    at freebox.waitApplicationGranted (/home/pi/freebox-caller-id/caller_id.js:30:13)
    at _getAuthorizeStatus (/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:487:12)
    at Request.request [as _callback] (/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:386:4)
    at Request.self.callback (/home/pi/freebox-caller-id/node_modules/request/request.js:186:22)

**Comment by jystervinou** [comment]
Normalement c'est l'appel à init qui stocke dans le fichier /tmp/callerid/freebox.json les token d'authorisation de se connecter à la box.

Le fichier n'est pas créé lors de l'appel à init ? (on peut refaire un init plusieurs fois)

**Comment by jystervinou** [comment]
Corrigé par un autre : 

> Résolu en remplaçant la ligne 134 ' fs.writeFileSync(path, json, callback); ' par ' fs.writeFileSync(path, json, null, null, null, callback); '

il faut que je fasse la modif de mon côté.

**Comment by alexisrgd** [comment]
Bonjour,

J'obtiens ce message au lancement du RPI :
Une idée?

nov. 02 20:48:38 servtest systemd[1]: Started FreeboxCallerID.
nov. 02 20:48:39 servtest node[1368]: fs.js:663
nov. 02 20:48:39 servtest node[1368]:   return binding.open(pathModule.toNamespacedPath(path),
nov. 02 20:48:39 servtest node[1368]:                  ^
nov. 02 20:48:39 servtest node[1368]: Error: ENOENT: no such file or directory, open '/tmp/callerid/freebox.json'
nov. 02 20:48:39 servtest node[1368]:     at Object.fs.openSync (fs.js:663:18)
nov. 02 20:48:39 servtest node[1368]:     at Object.fs.readFileSync (fs.js:568:33)
nov. 02 20:48:39 servtest node[1368]:     at new Freebox (/opt/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:65:22)
nov. 02 20:48:39 servtest node[1368]:     at getCalls (/opt/freebox-caller-id/caller_id.js:96:17)
nov. 02 20:48:39 servtest node[1368]:     at run (/opt/freebox-caller-id/caller_id.js:57:3)
nov. 02 20:48:39 servtest node[1368]:     at Object.<anonymous> (/opt/freebox-caller-id/caller_id.js:54:26)
nov. 02 20:48:39 servtest node[1368]:     at Module._compile (module.js:641:30)
nov. 02 20:48:39 servtest node[1368]:     at Object.Module._extensions..js (module.js:652:10)
nov. 02 20:48:39 servtest node[1368]:     at Module.load (module.js:560:32)
nov. 02 20:48:39 servtest node[1368]:     at tryModuleLoad (module.js:503:12)
nov. 02 20:48:39 servtest systemd[1]: freebox-caller-id.service: Main process exited, code=exited, status=1/FAILURE
nov. 02 20:48:39 servtest systemd[1]: freebox-caller-id.service: Unit entered failed state.
nov. 02 20:48:39 servtest systemd[1]: freebox-caller-id.service: Failed with result 'exit-code'.
nov. 02 20:48:39 servtest systemd[1]: freebox-caller-id.service: Service hold-off time over, scheduling restart.
nov. 02 20:48:39 servtest systemd[1]: Stopped FreeboxCallerID.
nov. 02 20:48:39 servtest systemd[1]: freebox-caller-id.service: Start request repeated too quickly.
nov. 02 20:48:39 servtest systemd[1]: Failed to start FreeboxCallerID.
nov. 02 20:48:39 servtest systemd[1]: freebox-caller-id.service: Unit entered failed state.
nov. 02 20:48:39 servtest systemd[1]: freebox-caller-id.service: Failed with result 'exit-code'.

**Comment by jystervinou** [comment]
Bonjour,

oui voir la modif ligne 134 juste au dessus.

merci de me dire si ok. (il faudra refaire init)

**Comment by alexisrgd** [comment]
Le fonctionnement est bon, seulement au reboot du serveur même message. Un paramètre à ajouter dans le systemd créé peut-être?
Est-il possible de raccourcir le délai de l'envoi du sms? Je le reçois environ 1 minute après la fin de l'appel.

**Comment by jystervinou** [comment]
Est-ce que par hasard, après le reboot, /tmp aurait été purgé??

l'envoi du sms, c'est juste un appel à l'url https://sms-api.free-mobile.fr/..... donc ça c'est quelques ms. ensuite le temps d'acheminement du sms de chez Free vers le téléphone je suppose que ça doit être variable... moi c'est quasi instantané pour le moment :-/

**Comment by jystervinou** [comment]
Tu peux essayer de changer dans le script le chemin du fichier où sont sauvegardé les paramètres de connexion à la box, et mettre un endroit autre que /tmp (remplacer  '/tmp/callerid/freebox.json' par un autre endroit, que le script aura le droit de créer.)

**Comment by aumgeo** [comment]
bonjour
excuser moi,  question tres bete, mais dans quel fichier il faut modifier la ligne 134 ?
(j'ai l'erreur apres node caller_id.js init)
merci

**Comment by jystervinou** [comment]
ça doit être dans le module node-freeboxos. je regarde ça tout de suite, je vais faire une nouvelle release. (j'utilise un fork de node-freeboxos, car j'ai du modifier des choses dedans pour le faire marcher)

**Comment by jystervinou** [comment]
ça y est, tu peux faire un "npm update" à la racine du répertoire du projet. 

relancer init, qui doit maintenant créer le fichier /tmp/callerid/freebox.json

**Comment by flimo44** [comment]
le fichier à modifier est : 
/home/pi/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js

Ligne 132  il me semble.

Sinon ça fonctionne bien pour moi et je reçois le SMS dès la première sonnerie. Donc très réactif :D

**Comment by aumgeo** [comment]
merci !
je fais un test ce soir apres le boulo, et je vous fait un retour.
je vais pas faire sonner le téléphone maintenant : tout le monde dors ;o))

**Comment by alexisrgd** [comment]
Effectivement après reboot, les dossiers sont bien présents, mais vides. Je vais modifier le dossier de destination (autre que '/tmp') et vous faire un retour 👍

**Comment by jystervinou** [comment]
Peut-être vaut-il mieux que je stocke ça dans le répertoire de l'appli ?

**Comment by flimo44** [comment]
Effectivement je pense que ce serait mieux que le /tmp.

Certains utilisent le /tmp en tmpfs. Donc à chaque reboot le dossier est purgé.

De plus ces données ne devrait  pas être temporaire.

Il serait bien de prévoir aussi d'installer "node caller_id.js"  comme service.

**Comment by alexisrgd** [comment]
Je pense comme flimo44 que ce serait préférable de tout stocker dans le même répertoire. Le répertoire /tmp est utilisé par beaucoup de programmes pour leur fichiers "temporaires".

**Comment by jystervinou** [comment]
OK.

Vous êtes obligés de les rebooter souvent vos Pi ?

**Comment by flimo44** [comment]
Je reboot rarement mes PI .

ça varie entre 1 mois et 4 mois en moyenne. Principalement après des mises à jours OS ou firmware

**Comment by alexisrgd** [comment]
Maintenant j'ai ce message après un reboot : 

systemd[1]:  Started FreeboxCallerID.
node[681]: { Error: Session failed !
node[681]:     at Request.request [as _callback] (/opt/freebox-caller-id/node_modules/node-fre
eboxos/lib/freebox.js:671:13)
node[681]:     at Request.self.callback (/opt/freebox-caller-id/node_modules/request/request.js:186:22)
node[681]:     at emitTwo (events.js:135:13)
node[681]:     at Request.emit (events.js:224:7)
node[681]:     at Request.<anonymous> (/opt/freebox-caller-id/node_modules/request/request.js:1163:10)
node[681]:     at emitOne (events.js:125:13)
node[681]:     at Request.emit (events.js:221:7)
node[681]:     at IncomingMessage.<anonymous> (/opt/freebox-caller-id/node_modules/request/request.js:1085:12)
node[681]:     at Object.onceWrapper (events.js:322:30)
node[681]:     at emitNone (events.js:120:20)
node[681]:   serverErrorCode: 'invalid_token',
node[681]:   response:
node[681]:    { uid: '90a140346837c1245b68b8723f196019',
node[681]:      success: false,
node[681]:      msg: 'Erreur d\'authentification de l\'application',
node[681]:      result:
node[681]:       { password_salt: 's80Tqs0TXc43odlnVkBlYfiqm2+P6rmh',
node[681]:         challenge: 'Hgrj4oGb1xTUzylxbnGQvsfBauPOlOLE' },
node[681]:      error_code: 'invalid_token' },
node[681]:   statusCode: 403,
node[681]:   canRetry: true }

Peu-être parce que je désactive l'option "Permettre les nouvelles demandes d'association" une fois la première effectuée sur freebox OS?

**Comment by jystervinou** [comment]
Ensuite, si tu fais un appel de test, ça marche ou pas ?

Lorsque le token de session n'est plus valable, node-freeeboxos en redemande un automatiquement. Donc même si invalid_token s'affiche, normalement ça continue de fonctionner..

**Comment by alexisrgd** [comment]
Effectivement même avec le message "invalid_token", le script fonctionne! Merci :)

**Comment by titithebad** [comment]
Bonjour,

Je suis avec un RPi 1 et donc un node v4.0.0 qui fonctionne avec l'arm.

Est-ce la bonne version ou je peux l'upgrader ?

Lorsque je lance le script node caller_id.js init, ma Freebox me demande bien le Non/Oui avec les flêches mais j'ai beau changer le DELAY dans le script ou le timeout de la commande init, voilà l'erreur que j'ai à chaque fois :

error= null app= { app_id: 'callerid',
  app_name: 'Caller ID',
  app_version: '0.0.1',
  device_name: 'Server',
  app_token: 'ygPOXsYlI9o2xaxOBBTv1sGcnM8mOFH8HVXnySzVicTJmHns5I5osuxU0fcISzN/',
  track_id: 6,
  logged_in: false,
  challenge: 'k3Ge0rrp4HgT5ryCnejUnrxFniAQWhJF',
  password: null,
  status: 'granted' }

Pourquoi ?

Merci

**Comment by jystervinou** [comment]
@titithebad hello, ce n'est pas une erreur en fait, c'est le message renvoyé par Freebox OS pour dire que l'autorisation a été accordée (status: 'granted'). 👍

**Comment by titithebad** [comment]
Merci mais pourquoi alors j'ai cette erreur quand je lance node caller_id.js ?
 fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/callerid/freebox.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at new Freebox (/home/pi/sms_freebox/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:66:22)
    at getCalls (/home/pi/sms_freebox/freebox-caller-id/caller_id.js:96:17)
    at run (/home/pi/sms_freebox/freebox-caller-id/caller_id.js:57:3)
    at Object.<anonymous> (/home/pi/sms_freebox/freebox-caller-id/caller_id.js:54:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

**Comment by jystervinou** [comment]
C'est que 'node caller_id.js init' n'a pas écrit le fichier /tmp/callerid/freebox.json. Il n'y a pas un autre message après le init ? Tu réponds bien Oui sur la Freebox ? 

Aussi, je ne sais pas à quand remonte ton "git checkout" mais tente un "**npm** update".

**Comment by titithebad** [comment]
Bonsoir,

Je viens de regarder un peu plus le script. Pourquoi mettre les fichiers dans /tmp ?

Sur les RPi pour économiser la carte SD, il est souvent conseillé de mettre en RAM les répertoires /tmp et /var/log.

Il n'est pas possible de mettre cela ailleurs ?

A chaque reboot du RPi, tous tes fichiers temporaires sont perdus....

Qu'en penses-tu ?

**Comment by jystervinou** [comment]
Je vais les mettre dans le répertoire de l'appli.

et surtout je ne vais plus avoir besoin que du fichier freebox.json...

**Comment by titithebad** [comment]
Parfait, c'est beaucoup mieux ainsi car d'autres applis touchent au répertoire /tmp.

Fais moi signe quand c'est fait que je teste. Rallonge aussi peut être les delay d'attente des réponses ?

**Comment by jystervinou** [comment]
Quels delais d'attente des réponses ?

**Comment by jystervinou** [comment]
Nouvelle version 0.5.0 avec nouveau fichier de conf dans config/default.json

Merci de vos retours. (genre : ça marche ?? :-) )

**Comment by jystervinou** [comment]
Attention le format du fichier de conf a un peu changé. Merci de repartir du default.json fourni. (il y a maintenant un élément 'freemobile' qui est un Array json, dans lequel vous pouvez mettre une ou plusieurs confs Free Mobile -- cf la doc sur la page d'accueil)

=> il faut créer un fichier config/local.json en vous inspirant de config/default.json (si vous modifiez directement default.json, les prochains 'git pull' peuvent looser)

Voir la doc de [Node Config](https://github.com/lorenwest/node-config/wiki/Configuration-Files) pour les noms de fichier de conf supportés.

**Comment by titithebad** [comment]
Pour le délais d'attente, tu n'as pas mis un genre de timeout au cas ou ?

Du coup j'ai l'impression que vu les changements, il vaut mieux tout repartir de zéro ?

**Comment by jystervinou** [comment]
oui, mais normalement il n'y a que le fichier de conf à modifier, et refaire un init.

Il n'y a pas de délai d'attente. Le script appelle Freebox OS toutes les secondes, et s'il y a un appel en cours, l'appel à l'API d'envoi du SMS est immédiat.

**Comment by alexisrgd** [comment]
Parfait, par défaut le texte passe au poil sur notification Android :+1:  (pas besoin d'ouvrir le SMS)

**Comment by jystervinou** [comment]
tu peux maintenant customiser le texte via le fichier de conf, cf la page d'accueil. Ca utilise la syntaxe de [http://olado.github.io/doT/index.html](http://olado.github.io/doT/index.html)

**Comment by titithebad** [comment]
J'ai une erreur quand je lance node caller_id.js : 
________________________________________________
   if (calls.length == 0) return setTimeout(run, DELAY);
             ^

TypeError: Cannot read property 'length' of undefined
    at /home/pi/sms_freebox/freebox-caller-id/caller_id.js:63:14
    at /home/pi/sms_freebox/freebox-caller-id/caller_id.js:177:12
    at Request._callback (/home/pi/sms_freebox/freebox-caller-id/node_modules/node-freeboxos/lib/freebox.js:938:4)
    at Request.self.callback (/home/pi/sms_freebox/freebox-caller-id/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/pi/sms_freebox/freebox-caller-id/node_modules/request/request.js:1163:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/pi/sms_freebox/freebox-caller-id/node_modules/request/request.js:1085:12)
_______________
Suite à la mise à jour, j'ai tout réinstallé et je suis avec la version node 4.8.6 qui fonctionne sur mon RPi 1. J'ai donc refait également node caller_id.js init et j'ai accepté sur ma freebox.

**Comment by jystervinou** [comment]
Hello,

il n'y a que ça comme erreur qui s'affiche ? 

je regarde.

**Comment by titithebad** [comment]
Oui que cela.

**Comment by jystervinou** [comment]
est-ce que freebox.json a bien été écrit sur le disque, dans le répertoire du projet ?

**Comment by titithebad** [comment]
oui je le vois dans le répertoire du projet et il est pas vide ! Je vois à la fin le granted

**Comment by jystervinou** [comment]
c'est un git clone tout nouveau ?

tu peux tenter un "npm update" à la racine ?

**Comment by titithebad** [comment]
Oui pour le git clone. J'ai tout refait.

même résultat suite au npm update.

Lors que je fait le node init, la freebox met du temps à me demander demander l'autorisation... Mais elle me la demande.

**Comment by jystervinou** [comment]
sans me le copier coller, il y a un fichier json qui a l'air correct dans freebox.json ?

**Comment by titithebad** [comment]
Oui, il ressemble a ca (j'ai mis toto dans les paramètres : 
{
        "app_id": "callerid",
        "app_name": "Caller ID",
        "app_version": "0.5.2",
        "device_name": "Server",
        "app_token": "toto",
        "track_id": 9,
        "logged_in": true,
        "challenge": "toto",
        "password": "toto",
        "status": "granted",
        "session_token": "toto",
        "permissions": {
                "parental": false,
                "explorer": true,
                "contacts": true,
                "downloader": true,
                "settings": false,
                "calls": true,
                "___home": true,
                "pvr": true,
                "tv": true
        }

**Comment by jystervinou** [comment]
C'est ici que calls est undefined, je ne comprends pas pourquoi :

https://github.com/jystervinou/freebox-caller-id/blob/master/caller_id.js#L177

**Comment by jystervinou** [comment]
tu as des appels récents dans la freebox ou liste vide ?

**Comment by titithebad** [comment]
Liste en 09 a priori vide.
Liste en 01 a priori au moins 1 appel car je viens de m'appeler depuis mon portable

**Comment by jystervinou** [comment]
et tj la même erreur  ?

si tu lances 

`
node caller_id lastcall
`

même erreur ?

**Comment by titithebad** [comment]
idem. Je viens de m'appeler au 01 et au 09 avant.

J'ai activé le SIP sur ma freebox également.

**Comment by jystervinou** [comment]
avec le sip activé, les appels sont aussi acheminé sur la freebox ?

**Comment by titithebad** [comment]
Ca je ne sais pas car ils arrivent vers mon portable quand je suis connecté en WiFI. Sinon vers la Freebox.

Je retente en m'appelant en mode non WiFI.

**Comment by titithebad** [comment]
C'est bon j'ai trouvé ton problème dans ton code : 
 - si la liste est vide ce qui était mon cas je pense, ca plante avec l'erreur
 - en mode SIP, les appels n'aboutissent pas à la Freebox mais directement sur mon portable (je viens de tester en mode non WiFi).

Du coup on mode classique quand j'appelle la Freebox au téléphone, la liste n'est plus vide et du coup je n'ai plus l'erreur mais : 

{ number: '06xxxxxxxx',
  type: 'missed',
  id: 26,
  duration: 6,
  datetime: 1510412653,
  contact_id: 0,
  line_id: 0,
  name: 'xxxxxxxx',
  new: true }

Je pense que quand on appelle la Freebox en 01 ou 09 cela ne change rien.

Qu'en penses-tu ?

**Comment by titithebad** [comment]
Je viens de tester et c'est bien cela

**Comment by jystervinou** [comment]
ok merci, je vais refaire un test de mon côté pour voir ce que renvoit Freebox.calls quand la liste est vide ('undefined' visiblement)

**Comment by titithebad** [comment]
Voilà !

le mode SIP nous a permis de trouver le soucis !

Regarde aussi quand on appelle la box en 09 ou en 01 si ca fait la même chose !

**Comment by jystervinou** [comment]
je n'ai plus le 09 depuis que je suis passé en dégroupage total il me semble..

**Comment by titithebad** [comment]
Tu as toujours un 09 même en dégroupage totale (j'ai cette config).

Autres soucis que tu peux voir : 
 - si j'exécute caller_id ailleurs que dans son répertoire genre : 
   cd /
   node ~/caller_id => j'ai une erreur

 - si j'exécute 2 fois node caller_id, j'ai une erreur aussi.

**Comment by jystervinou** [comment]
pour le premier, il ne doit pas trouver le fichier de conf.

pour le second, tu as quoi comme erreur ? (tu veux bien dire, que tu le lances en parallèle dans un autre shell ?)

**Comment by jystervinou** [comment]
ah oui, je dois confondre avec le fait que lorsque tu appelles quelqu'un, c'est le 09 qui s'affiche chez lui, et non le 01/02etc.. (ce qui est dommage)

**Comment by titithebad** [comment]
Oui pour la première erreur

Tu as l'erreur comme quoi tu fais un double accès à la Freebox.

Je sais pas si tu es capable de gérer ces erreurs en fait.... A l'utilisateur de faire gaffe.

**Comment by titithebad** [comment]
Comment faire pour pouvoir exécuter depuis n'importe quel répertoire la commande node caller_id.js ?

Je voudrais mettre cela en automatique après chaque redémarrage de mon RPi !

**Comment by jystervinou** [comment]
@titithebad Je viens de faire une modif pour que le fichier freebox.json soit trouvable, quel que soit l'endroit d'où le script est executé.

Dis-moi si ça marche, avec la dernière version 0.5.4

**Comment by jystervinou** [comment]
@titithebad  Nouvelle 0.5.5 avec le test pour le cas où il n'y a aucun appel dans l'historique.

**Comment by titithebad** [comment]
SI je teste depuis n'importe ou, j'ai cette erreur : 
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/pi/sms_freebox/freebox_caller_id/caller_id.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

Quand j'exécute depuis le répertoire ou c'est installé, aucune erreur.

J'ai tout réinstallé depuis le début pour etre sur d'avoir qqchose de propre

**Comment by jystervinou** [comment]
:-( Quelle commande exactement ?

**Comment by jystervinou** [comment]
J'ai cette exacte erreur si je ne tape pas exactement le bon chemin du script. il n'y aurait pas un _ à la place d'un - ou un truc du genre ?

`ls /home/pi/sms_freebox/freebox_caller_id/caller_id.js`

**Comment by titithebad** [comment]
Problème résolu je pense. JE sais pas faire la différence entre un _ et un -.....

Tu veux que je teste quoi du coup maintenant que ca fonctionne depuis n'importe quel répertoire ?

**Comment by jystervinou** [comment]
Je ne sais pas pourquoi j'ai mis un underscore dans le nom du script d'ailleurs.

Pour le moment, si tout semble fonctionner, rien :) Merci.

**Comment by titithebad** [comment]
Proposes-tu un fichier .log ?

Dans le temps (endurance), le process s'arrête et je ne sais pas pourquoi. J'aimerais pourvoir logguer les messages en fait dans un fichier.

**Comment by titithebad** [comment]
Il faut juste en paramètre un /var/log/... avec horodatage !

Et au lieu de faire un printf sur la console, faire un fprintf dans le fichier log ! Debug plus facile lors du plantage

**Comment by jystervinou** [comment]
@titithebad j'ai déjà utilisé ça : https://github.com/winstonjs/winston

**Comment by titithebad** [comment]
Mouai... J'aurais préféré fait dans l'application en elle même... Non ?

**Comment by jystervinou** [comment]
oui oui, ça s'utilise dans l'appli pour loguer, tu as ensuite le choix de l'endroit où ça logue, je suppose que je pourrai, en plus du mode par défaut, laisser configurer via le fichier de conf. (dans quel fichier, ou syslog etc..)

**Comment by titithebad** [comment]
Bon je vais voir ce que ca donne car caller_id plante on dirait dans le temps....

**Comment by jystervinou** [comment]
c'est le script qui plante et quitte, ou juste il ne marche plus (pas d'envoi de SMS) ? Parfois il ne trouve plus ma freebox (injoignable, je ne sais pas pourquoi ??), il faut que je vérifie si il continue à fonctionner normalement dans ces cas-là (je pense que oui, car je reçois toujours des SMS)

**Comment by titithebad** [comment]
Je ne vois plus le process tourner en fait via ps -edf. Je vais laisser mon putty dessus pour surveiller les messages et essayer de te filer le message d'erreur.

**Comment by titithebad** [comment]
J'essaie de faire node caller_id > sms.log

**Comment by jipere** [comment]
Bonjour, je viens de terminer l'installation sur un raspberry armv6, raspbian strecht-lite et node v8.9.0. ca marche. pour installer node v8:

wget https://nodejs.org/download/release/v8.9.0/node-v8.9.0-linux-armv6l.tar.gz
tar -xzf node-v8.9.0-linux-armv6l.tar.gz
cd node-v8.9.0-linux-armv6l/
sudo cp -R * /usr/local/
export PATH=$PATH:/usr/local/bin
pour verifier:
node -v
npm -v

**Comment by titithebad** [comment]
Il faut que je change de version de node suite à tes dernières modifs ?

**Comment by jystervinou** [comment]
Aucune idée, mais je dirais que si ça tournait avec node_freeboxos, ça devrait toujours le faire.

Pour le script qui s'arrête seul, je pense que c'est peut-être qu'il est tué lorsqu'il n'est plus rattaché au terminal d'où tu l'as lancé ?

Il faudrait trouver la façon la plus simple de le lancer (directement, et au boot)

**Comment by titithebad** [comment]
Bon je vais essayer avec une version plus récente de node alors.

Oui tu as sans doute raison. Je le lance avec le & à la fin.

C'est une tâche cron qui le lance (cron.daily).

**Comment by jystervinou** [comment]
C'est ce que je fais aussi pour le moment, et effectivement, il disparait au bout d'un moment ;-/

**Comment by titithebad** [comment]
C'est un plantage tu crois ou bien un service qui n'est pas lancé ?

**Comment by jystervinou** [comment]
Je dirais pas tant un plantage qu'un arrêt suite à la disparition du processus qui l'a lancé ?

**Comment by titithebad** [comment]
node qui s'arrête ?

Tu log tout cela dans ton appli ?

**Comment by titithebad** [comment]
Je viens de réinstaller node.

La config fonctionne mais quand j'appelle chez moi, voilà le message d'erreur : 

pi@bureau:~ $ events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/pico2wave ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

En effet dans /usr/bin, pico2wave n'existe pas sur mon RPI. Je suis avec une distribution 8.0.

**Comment by jystervinou** [comment]
Tu l'as installé à quel endroit ?

Tu peux spécifier le chemin dans la conf.

**Comment by jystervinou** [comment]
```
sudo apt-get install libttspico-utils

which pico2wave
whereis pico2wave

```

**Comment by titithebad** [comment]
Il est installé de base sur la 9.0 de Debian ou il a fallu que tu le rajoutes ?

**Comment by jystervinou** [comment]
j'ai une 8 car j'ai installé retropie en fait.

et oui il a fallu que je l'installe avec la commande ci-dessus.

**Comment by titithebad** [comment]
Sinon ca fonctionne mais j'ai cette erreur/warning : 
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/sox ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jystervinou** [comment]
`sudo apt-get install sox`

?

**Comment by jystervinou** [comment]
La [doc](https://github.com/jystervinou/freebox-caller-id) est à jour avec tous les utilitaires à installer.

Enfin normalement :)

**Comment by titithebad** [comment]
Oui c'est bon ! j'utilise pas le speaker de Fbx.

Comment s'appelle les log ?

J'ai 2 fichiers log de taille 0.

Sinon j'ai un fichier package-lock.json, c'est quoi ?

Enfin, j'ai regardé : l'application ne fonctionne pas mais le process tourne quand meme quand je regarde via ps -edf. Une idée du soucis ?

**Comment by Laurent-84** [comment]
Bonjour,
Erreur à l'installation (a noter: Effectué sur PI3 avec Jeedom):
**************************************************************************
sudo cp ffmpeg-3.4-armhf-32bit-static/ff* /usr/local/bin/
cp: impossible d'▒valuer 'ffmpeg-3.4-armhf-32bit-static/ff*': Aucun fichier ou dossier de ce type
**************************************************************************


**************************************************************************
node caller_id.js init
/home/pi/freebox-caller-id/node_modules/config/lib/config.js:946
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '/home/pi/freebox-caller-id/config/local.json': SyntaxError: Unexpected token : in JSON at position 16
    at Config.util.parseFile (/home/pi/freebox-caller-id/node_modules/config/lib/config.js:946:11)
    at /home/pi/freebox-caller-id/node_modules/config/lib/config.js:715:28
    at Array.forEach (native)
    at /home/pi/freebox-caller-id/node_modules/config/lib/config.js:711:14
    at Array.forEach (native)
    at Config.util.loadFileConfigs (/home/pi/freebox-caller-id/node_modules/config/lib/config.js:710:13)
    at new Config (/home/pi/freebox-caller-id/node_modules/config/lib/config.js:135:27)
    at Object.<anonymous> (/home/pi/freebox-caller-id/node_modules/config/lib/config.js:1780:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
**************************************************************************

Merci.

**Comment by jystervinou** [comment]
Bonjour,

Dans les deux cas, les fichiers ne sont pas présents.

Ca donne quoi :

pwd
ls

?

Jean-Yves

**Comment by Laurent-84** [comment]
Bonjour Jean-Yves,

Voici ce que donne les commandes:

pi@raspberrypi:~ $ pwd
/home/pi

pi@raspberrypi:~ $ ls
ffmpeg-3.4.1-armhf-32bit-static
ffmpeg-release-armhf-32bit-static.tar.xz
ffmpeg-release-armhf-32bit-static.tar.xz.1
ffmpeg-release-armhf-32bit-static.tar.xz.2
freebox-caller-id

**Comment by jystervinou** [comment]
OK, la version de ffmpeg est passée en 3.4.1 au lieu de 3.4 dans ma doc.

Peux-tu réessayer en rajoutant le .1  quand il y a ffmpeg-3.4 ?

**Comment by Laurent-84** [comment]
Bonjour,
 sudo cp ffmpeg-3.4.1-armhf-32bit-static/ff* /usr/local/bin/ ==> OK

Par contre: "node caller_id.js init" toujours erreur:
Edit: Manquait '{' au debut de mon local.json

Cela fonctionne maintenant;
**Merci.**

**Comment by jystervinou** [comment]
Merci pour le retour. Il faut que je mette la doc à jour pour ffmpeg-3.4.1.
