### ISSUE TITLE
le script fonctionne toujours ?

### ISSUE THREAD

**Issue by hornet49** [jystervinou/freebox-caller-id#14]
Bonjour,

est ce que le script fonctionne toujours chez vous ? car j'ai une erreur au lancement :-/ peut être du à une mise a jour de la freebox ???
Merci pour vos retour.

**Comment by jystervinou** [comment]
Bonjour,

Quelle est l’erreur ?

Jean-Yves

**Comment by hornet49** [comment]
bon déja si ça fonctionne toujours c'est cool !!! merci pour l'info.

voici ce que j'ai (pour rappel je tourne sous windows 7)

C:\Users\Salon>node caller_id.js
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new Freebox (C:\Users\Salon\node_modules\node-freeboxos\lib\freebox.js:68
:23)
    at getCalls (C:\Users\Salon\caller_id.js:338:17)
    at run (C:\Users\Salon\caller_id.js:102:3)
    at Object.<anonymous> (C:\Users\Salon\caller_id.js:99:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Merci d'avance pour ton aide ;-)

**Comment by hornet49** [comment]
autant pour moi jean yves, j'ai refais le init avec la freebox et ça refonctionne.
bizard qu'il l'avait perdu.
désoler pour la fausse panne lol
tu sais pas si on peut adapter le script pour qu'il tourne sur une box domotique comme l'EEDOMUS ?
ça serai vraiment top du top ça !!

**Comment by jystervinou** [comment]
Je ne connais pas du tout ces box. C'est du linux dessus ? Et quel processeur ? de l'ARM ?
