### ISSUE TITLE
Erreur ?

### ISSUE THREAD

**Issue by titithebad** [jystervinou/freebox-caller-id#15]
Salut,

J'ai réinstallé sur un RPi et voilà l'erreur que j'ai quand je m'appelle.

info: Sending notifications...
info: Sending 1 SMS...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/pico2wave ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Sais-tu pourquoi ?

J'ai l'impression que cela parle de pico2wave or dans mon fichier de conf, je n'ai aucune demande de son. Je souhaite que l'envoi d'un SMS !

Merci

**Comment by jystervinou** [comment]
Hello,

As-tu installé ça ?

sudo apt-get install libttspico-utils

(même si tu ne veux utiliser que la fonction SMS)

A+

**Comment by titithebad** [comment]
Salut,

Oui j'ai installé les 2 petits utilitaires et cela fonctionne. Dommage que
ton appli plante car pas installé.
Thierry BADEUIL
