### ISSUE TITLE
Créer un fichier de log

### ISSUE THREAD

**Issue by jystervinou** [jystervinou/freebox-caller-id#7]
Cf [demande](https://github.com/jystervinou/freebox-caller-id/issues/1#issuecomment-345170424) de @titithebad 

Ce serait mieux avec un vrai fichier de log...

**Comment by jystervinou** [comment]
https://github.com/jystervinou/freebox-caller-id/issues/1#issuecomment-345289245

**Comment by jystervinou** [comment]
C'est fait dans la 0.7.2 cc @titihead

**Comment by titithebad** [comment]
Salut,

Ca ne fonctionne pas et voilà l'erreur  quand je fais node caller_id.js init

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/pi/sms_freebox/freebox-caller-id/config/caller_id.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

Remarque : mon fichier local n'utilise pas les options ffmpeg etc.... J'ai juste laisser mes identifiants free.

**Comment by jystervinou** [comment]
> Error: Cannot find module '/home/pi/sms_freebox/freebox-caller-id/config/caller_id.js'

caller_id.js est cherché dans le répertoire config/   (??)

Quelle commande tu lances ? (et dans quel répertoire)

**Comment by jystervinou** [comment]
Note : si tu fais un "git pull" dans le répertoire principal "/home/pi/sms_freebox/freebox-caller-id/", pas la peine de refaire un git clone complet de tout le projet.

**Comment by titithebad** [comment]
Oui pour le répertoire config/

Je lance la commande node dans le répertoire racine ou il y a le readme il me semble. Je vérifie ce soir !

J'aime bien repartir quelque chose de propre ;).!

**Comment by titithebad** [comment]
Est-ce que le fichier local.json est forcément avec le nouveau format ou le fait de jouer sur le speaker de la fbx est optionnel ?

**Comment by jystervinou** [comment]
Optionnel.

**Comment by titithebad** [comment]
Bon j'ai tout refait propre et voilà l'erreur : 
pi@bureau:~/sms_freebox/freebox-caller-id $ node caller_id.js
/home/pi/sms_freebox/freebox-caller-id/node_modules/winston/lib/winston/common.js:9
const { format } = require('util');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/sms_freebox/freebox-caller-id/node_modules/winston/lib/winston.js:9:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
